spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//34.64.231.109:1521/XE
    username: kbs
    password: power
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher